version: "2"

sql:
  - engine: "postgresql"
    schema: "./schema"
    queries: "./queries"
    gen:
      go:
        package: "gen"
        out: "./gen"
        sql_package: "pgx/v5"
        emit_interface: true
        emit_empty_slices: true
        emit_exact_table_names: false