# .air.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
exclude_file = []
follow_symlink = true
kill_delay = 500

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[env]
ENV = "development"
PORT = "8080"
DEBUG = "true"
