basePath: /api/v1
definitions:
  github_com_edynnt_veloras-api_internal_auth_controller_dto.UserRegisterReq:
    properties:
      address:
        type: string
      country:
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      language:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
  github_com_edynnt_veloras-api_pkg_response.APIError:
    properties:
      err: {}
      errorFlag:
        type: boolean
      message:
        type: string
      statusCode:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server for a Go Drunk Backend API, demonstrating DDD principles.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Drunk Backend API by DDD
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new account with username, password, email, and other
        details
      parameters:
      - description: User registration request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_edynnt_veloras-api_internal_auth_controller_dto.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: Returns created account ID
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/github_com_edynnt_veloras-api_pkg_response.APIError'
        "409":
          description: Registration failed due to conflict
          schema:
            $ref: '#/definitions/github_com_edynnt_veloras-api_pkg_response.APIError'
      summary: Register a new user
      tags:
      - Auth
swagger: "2.0"
